export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const DELETE_ADDRESS_LOADING = 'DELETE_ADDRESS_LOADING';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';

export const ADD_ADDRESS_LOADING = 'ADD_ADDRESS_LOADING';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';

export const UPDATE_ADDRESS_LOADING = 'UPDATE_ADDRESS_LOADING';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';

export const UPDATE_SELECTED_ADDRESS_LOADING = 'UPDATE_SELECTED_ADDRESS_LOADING';
export const UPDATE_SELECTED_ADDRESS_SUCCESS = 'UPDATE_SELECTED_ADDRESS_SUCCESS';
export const UPDATE_SELECTED_ADDRESS_FAIL = 'UPDATE_SELECTED_ADDRESS_FAIL';